//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForestEntities : DbContext
    {
        public ForestEntities()
            : base("name=ForestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveItem> ActiveItems { get; set; }
        public virtual DbSet<ActivePhoto> ActivePhotoes { get; set; }
        public virtual DbSet<ActiveUnitSetting> ActiveUnitSettings { get; set; }
        public virtual DbSet<ADCenter> ADCenters { get; set; }
        public virtual DbSet<ADDown> ADDowns { get; set; }
        public virtual DbSet<ADMain> ADMains { get; set; }
        public virtual DbSet<ADMobile> ADMobiles { get; set; }
        public virtual DbSet<ADMobileBlock> ADMobileBlocks { get; set; }
        public virtual DbSet<ADRight> ADRights { get; set; }
        public virtual DbSet<ADRightDown> ADRightDowns { get; set; }
        public virtual DbSet<ADSet> ADSets { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ColumnSetting> ColumnSettings { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EventListItem> EventListItems { get; set; }
        public virtual DbSet<EventListUnitSetting> EventListUnitSettings { get; set; }
        public virtual DbSet<F_HashTag_Type> F_HashTag_Type { get; set; }
        public virtual DbSet<F_Index> F_Index { get; set; }
        public virtual DbSet<F_Index_Img> F_Index_Img { get; set; }
        public virtual DbSet<F_MessageModel> F_MessageModel { get; set; }
        public virtual DbSet<F_Sub_HashTag_Type> F_Sub_HashTag_Type { get; set; }
        public virtual DbSet<F_Thingtodo_Index> F_Thingtodo_Index { get; set; }
        public virtual DbSet<F_Thingtodo_Type> F_Thingtodo_Type { get; set; }
        public virtual DbSet<FileDownloadItem> FileDownloadItems { get; set; }
        public virtual DbSet<FileDownloadUnitSetting> FileDownloadUnitSettings { get; set; }
        public virtual DbSet<FormInput> FormInputs { get; set; }
        public virtual DbSet<FormSelItem> FormSelItems { get; set; }
        public virtual DbSet<FormSetting> FormSettings { get; set; }
        public virtual DbSet<FormUnitSetting> FormUnitSettings { get; set; }
        public virtual DbSet<ForumUnitSetting> ForumUnitSettings { get; set; }
        public virtual DbSet<FreeZoneContent> FreeZoneContents { get; set; }
        public virtual DbSet<FreeZoneTitle> FreeZoneTitles { get; set; }
        public virtual DbSet<GroupActive> GroupActives { get; set; }
        public virtual DbSet<GroupFileDownload> GroupFileDownloads { get; set; }
        public virtual DbSet<GroupMessage> GroupMessages { get; set; }
        public virtual DbSet<GroupPatent> GroupPatents { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<GroupVideo> GroupVideos { get; set; }
        public virtual DbSet<Img> Imgs { get; set; }
        public virtual DbSet<Lang> Langs { get; set; }
        public virtual DbSet<LangKey> LangKeys { get; set; }
        public virtual DbSet<LangKeyUnit> LangKeyUnits { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MessageItem> MessageItems { get; set; }
        public virtual DbSet<MessageUnitSetting> MessageUnitSettings { get; set; }
        public virtual DbSet<ModelActiveEditMain> ModelActiveEditMains { get; set; }
        public virtual DbSet<ModelEventListMain> ModelEventListMains { get; set; }
        public virtual DbSet<ModelFileDownloadMain> ModelFileDownloadMains { get; set; }
        public virtual DbSet<ModelFormMain> ModelFormMains { get; set; }
        public virtual DbSet<ModelLangMain> ModelLangMains { get; set; }
        public virtual DbSet<ModelMessageMain> ModelMessageMains { get; set; }
        public virtual DbSet<ModelPageEditMain> ModelPageEditMains { get; set; }
        public virtual DbSet<ModelPatentMain> ModelPatentMains { get; set; }
        public virtual DbSet<ModelVideoMain> ModelVideoMains { get; set; }
        public virtual DbSet<ModelWebsiteMapMain> ModelWebsiteMapMains { get; set; }
        public virtual DbSet<PageIndexItem> PageIndexItems { get; set; }
        public virtual DbSet<PageIndexSetting> PageIndexSettings { get; set; }
        public virtual DbSet<PageLayout> PageLayouts { get; set; }
        public virtual DbSet<PageUnitSetting> PageUnitSettings { get; set; }
        public virtual DbSet<PatentItem> PatentItems { get; set; }
        public virtual DbSet<PatentUnitSetting> PatentUnitSettings { get; set; }
        public virtual DbSet<SEO> SEOs { get; set; }
        public virtual DbSet<SiteConfig> SiteConfigs { get; set; }
        public virtual DbSet<SiteFlow> SiteFlows { get; set; }
        public virtual DbSet<SiteLayout> SiteLayouts { get; set; }
        public virtual DbSet<SiteList> SiteLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VideoItem> VideoItems { get; set; }
        public virtual DbSet<VideoUnitSetting> VideoUnitSettings { get; set; }
        public virtual DbSet<AdminFunction> AdminFunctions { get; set; }
        public virtual DbSet<LinkItem> LinkItems { get; set; }
        public virtual DbSet<ZipCode> ZipCodes { get; set; }
        public virtual DbSet<F_Destination_Type> F_Destination_Type { get; set; }
        public virtual DbSet<Destination_Index> Destination_Index { get; set; }
        public virtual DbSet<Destination_MapLegend> Destination_MapLegend { get; set; }
    }
}
