
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebSiteProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class F_HashTag_Type
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public F_HashTag_Type()
    {

        this.F_Sub_HashTag_Type = new HashSet<F_Sub_HashTag_Type>();

        this.RecommendedTrips_HashTag_Type = new HashSet<RecommendedTrips_HashTag_Type>();

    }


    public int HashTag_Type_ID { get; set; }

    public string HashTag_Type_Name { get; set; }

    public string HashTag_Description { get; set; }

    public Nullable<System.DateTime> HashTag_CreateTime { get; set; }

    public string HashTag_Type_Link { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<F_Sub_HashTag_Type> F_Sub_HashTag_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RecommendedTrips_HashTag_Type> RecommendedTrips_HashTag_Type { get; set; }

}

}
