
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebSiteProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FormSetting
{

    public int ID { get; set; }

    public Nullable<int> ItemID { get; set; }

    public string FormDesc { get; set; }

    public string ConfirmContent { get; set; }

    public string SenderName { get; set; }

    public string SenderEMail { get; set; }

    public string SenderTitle { get; set; }

    public string ReceiveMail { get; set; }

    public string AdminSenderName { get; set; }

    public string AdminSenderEMail { get; set; }

    public string AdminSenderTitle { get; set; }

}

}
