
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebSiteProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Lang
{

    public int ID { get; set; }

    public Nullable<int> Lang_ID { get; set; }

    public Nullable<int> Site_ID { get; set; }

    public Nullable<int> Sort { get; set; }

    public Nullable<int> Area_id { get; set; }

    public string Lang_Name { get; set; }

    public string Disp_Name { get; set; }

    public string Domain_Type { get; set; }

    public string Sub_Domain_Name { get; set; }

    public string Indep_Domain_Name { get; set; }

    public string Content_Source { get; set; }

    public Nullable<int> Link_Lang_ID { get; set; }

    public string Link_Href { get; set; }

    public string Img_Name_Ori { get; set; }

    public string Img_Name_Thumb { get; set; }

    public Nullable<int> Img_Name_Height { get; set; }

    public string Img_Name_Ori2 { get; set; }

    public string Img_Name_Thumb2 { get; set; }

    public Nullable<int> Img_Name_Height2 { get; set; }

    public string Img_Name_Ori3 { get; set; }

    public string Img_Name_Thumb3 { get; set; }

    public Nullable<int> Img_Name_Height3 { get; set; }

    public string Img_Name_Ori10 { get; set; }

    public string Img_Name_Thumb10 { get; set; }

    public string Pda_Footer_Text { get; set; }

    public string Index_Text { get; set; }

    public string Footer_Text { get; set; }

    public Nullable<bool> Acc_Check_Passed { get; set; }

    public Nullable<bool> Acc_Check_Passed2 { get; set; }

    public Nullable<bool> Readonly { get; set; }

    public Nullable<bool> Enabled { get; set; }

    public Nullable<bool> Published { get; set; }

    public Nullable<bool> Deleted { get; set; }

    public Nullable<System.DateTime> UpdateDatetime { get; set; }

    public string UpdateUser { get; set; }

}

}
