//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_LEGEND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_LEGEND()
        {
            this.Destination_Index = new HashSet<Destination_Index>();
        }
    
        public int Destination_MAP_LEGEND_ID { get; set; }
        public string Destination_MAP_LEGEND_Name { get; set; }
        public string Destination_Img { get; set; }
        public string Destination_Img_Mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destination_Index> Destination_Index { get; set; }
    }
}
