//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public Nullable<int> LangID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> MenuType { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> ModelItemID { get; set; }
        public Nullable<int> LinkMode { get; set; }
        public Nullable<int> ShowMode { get; set; }
        public Nullable<int> OpenMode { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MenuName { get; set; }
        public string ImgNameOri { get; set; }
        public string ImgShowName { get; set; }
        public string ImgNameThumb { get; set; }
        public Nullable<int> WindowWidth { get; set; }
        public Nullable<int> WindowHeight { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUser { get; set; }
        public string LinkUrl { get; set; }
        public string LinkUploadFileName { get; set; }
        public string LinkUploadFilePath { get; set; }
        public string DisplayName { get; set; }
        public string ICon { get; set; }
    }
}
