//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message10Hash
    {
        public int Message10Hash_ID { get; set; }
        public string Message10Hash_1H { get; set; }
        public string Message10Hash_2H { get; set; }
        public string Message10Hash_3H { get; set; }
        public string Message10Hash_4H { get; set; }
        public string Message10Hash_5H { get; set; }
        public string Message10Hash_6H { get; set; }
        public string Message10Hash_7H { get; set; }
        public string Message10Hash_8H { get; set; }
        public string Message10Hash_9H { get; set; }
        public string Message10Hash_10H { get; set; }
        public Nullable<int> MessageItem_ID { get; set; }
    }
}
