
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebSiteProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PageIndexSetting
{

    public int ID { get; set; }

    public Nullable<int> Lang_ID { get; set; }

    public Nullable<bool> IsFirstPage { get; set; }

    public Nullable<bool> IsInPage { get; set; }

    public Nullable<int> ShowCount { get; set; }

    public string HtmlContent { get; set; }

    public string Column1 { get; set; }

    public string Column2 { get; set; }

    public string Column3 { get; set; }

    public string Column4 { get; set; }

    public string Column5 { get; set; }

    public string Column6 { get; set; }

    public string Column7 { get; set; }

    public string Column8 { get; set; }

    public string Column9 { get; set; }

    public string Column10 { get; set; }

    public string Column11 { get; set; }

    public string Column12 { get; set; }

    public string Column13 { get; set; }

    public string Column14 { get; set; }

    public string Column15 { get; set; }

    public string Column16 { get; set; }

    public string Column17 { get; set; }

    public string Column18 { get; set; }

    public string Column19 { get; set; }

    public string Column20 { get; set; }

    public string Column21 { get; set; }

}

}
