
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebSiteProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RecommendedTrip_Travel
{

    public int RecommendedTrip_Travel_ID { get; set; }

    public Nullable<int> RecommendedTrip_ID { get; set; }

    public string RecommendedTrip_Travel_Title { get; set; }

    public string RecommendedTrip_Travel_Content { get; set; }

    public string RecommendedTrip_Travel_Img { get; set; }

    public string RecommendedTrip_Travel_Img_Description { get; set; }

    public string RecommendedTrip_Travel_Link { get; set; }

    public string RecommendedTrips_Travel_LinkUrlDesc { get; set; }

    public Nullable<System.DateTime> RecommendedTrips_Travel_StarDay { get; set; }

    public Nullable<System.DateTime> RecommendedTrips_Travel_EndDay { get; set; }

    public Nullable<int> Sort { get; set; }

    public Nullable<int> InFront { get; set; }



    public virtual RecommendedTrip RecommendedTrip { get; set; }

}

}
