
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebSiteProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SEO
{

    public int ID { get; set; }

    public string TypeName { get; set; }

    public Nullable<int> TypeID { get; set; }

    public Nullable<int> Lang_ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Keywords1 { get; set; }

    public string Keywords2 { get; set; }

    public string Keywords3 { get; set; }

    public string Keywords4 { get; set; }

    public string Keywords5 { get; set; }

    public string Keywords6 { get; set; }

    public string Keywords7 { get; set; }

    public string Keywords8 { get; set; }

    public string Keywords9 { get; set; }

    public string Keywords10 { get; set; }

}

}
