//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteLayout
    {
        public int ID { get; set; }
        public Nullable<int> LangID { get; set; }
        public string LogoImgNameOri { get; set; }
        public string LogoImgShowName { get; set; }
        public string LogoImgNameThumb { get; set; }
        public Nullable<int> LogoImgHeight { get; set; }
        public string FirstPageImgNameOri { get; set; }
        public string FirstPageImgShowName { get; set; }
        public string FirstPageImgNameThumb { get; set; }
        public Nullable<int> FirstPageImgHeight { get; set; }
        public string InsidePageImgNameOri { get; set; }
        public string InsidePageImgShowName { get; set; }
        public string InsidePageImgNameThumb { get; set; }
        public Nullable<int> InsidePageImgHeight { get; set; }
        public string HtmlContent { get; set; }
        public string FowardImgNameOri { get; set; }
        public string FowardImgShowName { get; set; }
        public string FowardImgNameThumb { get; set; }
        public string FowardHtmlContent { get; set; }
        public string PrintImgNameOri { get; set; }
        public string PrintImgShowName { get; set; }
        public string PrintImgNameThumb { get; set; }
        public string PrintHtmlContent { get; set; }
        public string Page404HtmlContent { get; set; }
        public string Page404Title { get; set; }
        public string SType { get; set; }
        public string InnerLogoImgNameOri { get; set; }
        public string InnerLogoImgShowName { get; set; }
        public string InnerLogoImgNameThumb { get; set; }
        public Nullable<int> InnerLogoImgHeight { get; set; }
        public string PublishContent { get; set; }
    }
}
