//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteConfig
    {
        public int ID { get; set; }
        public string Login_Title { get; set; }
        public string Img_Name_Ori1 { get; set; }
        public string Img_Name_Thumb1 { get; set; }
        public string Img_Name_Ori2 { get; set; }
        public string Img_Name_Thumb2 { get; set; }
        public string Comp_Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public string Page_Title { get; set; }
        public string Img_Name_Ori3 { get; set; }
        public string Img_Name_Thumb3 { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUser { get; set; }
        public string MailServerIP { get; set; }
        public Nullable<int> Port { get; set; }
        public string EMailAccount { get; set; }
        public string EMailPassword { get; set; }
        public Nullable<bool> IsAuthMailServer { get; set; }
        public string QuestionnaireFinishDesc { get; set; }
        public string InvoiceDesc { get; set; }
        public string InvoiceMailSender { get; set; }
        public string InvoiceMailSenderMail { get; set; }
        public string InvoiceMailSenderTitle { get; set; }
        public Nullable<int> FirstPageMaxLinkItem { get; set; }
    }
}
